### ISSUE TITLE
get_multi not working

### ISSUE THREAD

**Issue by GoogleCodeExporter** [nrich/luamemcached#2]
```
foo = mmc:get_multi("ua_1", "ua_2");
for i,v in ipairs(foo) do print(i,v) end

..nothing

print(mmc:get("ua_1")) works
```

Original issue reported on code.google.com by `msporleder@gmail.com` on 16 Mar 2011 at 8:25

**Comment by nrich** [comment]
The code:

for i,v in pairs(foo) do print(i,v) end

works. ipairs doesn't work because the table is not numerically indexed.
